name: Test1

on: [push]

jobs:
  build:

    runs-on:  ubuntu-latest
    
     steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}
